import {IProject} from '../interface/IProject';

export const cardData: IProject[] = [
    {
        query: 'android-calculator',
        title: 'Calculator',
        badges: ['ANDROID', 'JAVA'],
        text: 'Native Android app programmed in Java and designed in Android Studio. Design inspired by Apple.',
        img: '/../public/project_calculator.gif',
        github: 'https://github.com/armenmerzaian/androidcalculator',
        learnMore: '/projects/android-calculator',
        launch: 'https://github.com/armenmerzaian/androidcalculator/blob/master/SimpleCalculator.apk',
        images: ['/../public/project_carrental.gif', '/../public/project_fp.gif', '/../public/project_senecasocial.gif', '/../public/project_weather.gif'],
        desc_block_1: [
            'This is a native Android app programmed in Java and designed in Android Studio. The design is inspired by Apple. The app supports basic arithmetic operations, as well as the ability to clear the screen and delete the last character. The app also supports the use of the backspace key on the keyboard.',
            'The app was designed to be as simple as possible, with a minimalistic design. The app is also fully responsive, and can be used on any Android device.',
            'The app was programmed using Android Studio, and the code is available on GitHub. The app is also available for download on GitHub'  
        ],
        desc_block_2: [
            'The app was programmed using Android Studio, and the code is available on GitHub. The app is also available for download on GitHub',
            'The app was programmed using Android Studio, and the code is available on GitHub. The app is also available for download on GitHub',
            'The app was programmed using Android Studio, and the code is available on GitHub. The app is also available for download on GitHub',
        ],
    },
    {   
        query: 'first-picture-whse', 
        title: 'First Picture Frame Warehouse',
        badges: ['WEB','GATSBY', 'REACT', 'HTML', 'TAILWIND CSS'],
        text: 'Built from the ground-up a new website for a local business. The website is built with Gatsby, React, HTML, and TailwindCSS.',
        img: '/../public/project_fp.gif',
        github: 'https://github.com/armenmerzaian/firstpictureframewhse.github.io',
        learnMore: '/projects/first-picture-whse',
        launch: 'https://firstpictureframewhse-github-io.vercel.app/',
        images: [],
        desc_block_1: [],
        desc_block_2: [],
    },
    {
        query: 'weather-app',
        title: 'Weather App',
        badges: ['WEB', 'REACT', 'HTML', 'BOOTSTRAP CSS', 'REST API'],
        text: 'Created a weather app using React, Bootstrap, and a REST API. Supports search and geolocation.',
        img: '/../public/project_weather.gif',
        github: 'https://github.com/armenmerzaian/weather-app',
        learnMore: '/projects/weather-app',
        launch: 'https://taupe-llama-46f0dd.netlify.app',
        images: [],
        desc_block_1: [],
        desc_block_2: [],
    },
    {
        query: 'seneca-social',
        title: 'Seneca Social',
        badges: ['ANDROID','FLUTTER', 'DART', 'FIREBASE', 'FIRESTORE','REST API'],
        text: 'A full stack social media app built with Flutter and Firebase. Supports user authentication, posting, commenting, and more!',
        img: '/../public/project_senecasocial.gif',
        github: 'https://github.com/armenmerzaian/seneca-social',
        learnMore: '/projects/seneca-social',
        launch: '',
        images: [],
        desc_block_1: [],
        desc_block_2: [],
    },
    {
        query: 'car-rental',
        title: 'Car Rental',
        badges: ['IOS','ANGULAR', 'TYPESCRIPT', 'IONIC'],
        text: 'An Angular front-end for a car rental app. Demonstrates the power of Ionic as a mobile app framework.',
        img: '/../public/project_carrental.gif',
        github: 'https://github.com/armenmerzaian/car-rental',
        learnMore: '/projects/car-rental',
        launch: '',
        images: [],
        desc_block_1: [],
        desc_block_2: [],
    },
]