import {IProject} from '../interface/IProject';

export const cardData: IProject[] = [
    {
        title: 'Card 1',
        badges: ['badge1', 'badge2'],
        text: 'This is card 1',
        img: 'https://picsum.photos/500/',
        github: '',
        learnMore: '',
        launch: '',
        images: [],
        description: '',
    },
    {    
        title: 'Card 2',
        badges: ['badge1', 'badge2'],
        text: 'This is card 2',
        img: 'https://picsum.photos/500/',
        github: '',
        learnMore: '',
        launch: '',
        images: [],
        description: '',
    },
    {
        title: 'Card 3',
        badges: ['badge1', 'badge2'],
        text: 'This is card 3',
        img: 'https://picsum.photos/500/',
        github: '',
        learnMore: '',
        launch: '',
        images: [],
        description: '',
    },
    {
        title: 'Card 4',
        badges: ['badge1', 'badge2'],
        text: 'This is card 4',
        img: 'https://picsum.photos/500/',
        github: '',
        learnMore: '',
        launch: '',
        images: [],
        description: '',
    },
    {
        title: 'Card 5',
        badges: ['badge1', 'badge2'],
        text: 'This is card 5',
        img: 'https://picsum.photos/500/',
        github: '',
        learnMore: '',
        launch: '',
        images: [],
        description: '',
    },
]