import {IProject} from '../interface/IProject';

export const cardData: IProject[] = [
    {
        title: 'Calculator',
        badges: ['ANDROID', 'JAVA'],
        text: 'Native Android app programmed in Java and designed in Android Studio. Design inspired by Apple.',
        img: '/../public/project_calculator.gif',
        github: 'https://github.com/armenmerzaian/androidcalculator',
        learnMore: '',
        launch: 'https://github.com/armenmerzaian/androidcalculator/blob/master/SimpleCalculator.apk',
        images: [],
        description: '',
    },
    {    
        title: 'First Picture Frame Warehouse',
        badges: ['WEB','GATSBY', 'REACT', 'HTML', 'TAILWIND CSS'],
        text: 'Built from the ground-up a new website for a local business. The website is built with Gatsby, React, HTML, and TailwindCSS.',
        img: '/../public/project_fp.gif',
        github: 'https://github.com/armenmerzaian/firstpictureframewhse.github.io',
        learnMore: '',
        launch: 'https://firstpictureframewhse-github-io.vercel.app/',
        images: [],
        description: '',
    },
    {
        title: 'Weather App',
        badges: ['WEB', 'REACT', 'HTML', 'BOOTSTRAP CSS', 'REST API'],
        text: 'Created a weather app using React, Bootstrap, and a REST API. Supports search and geolocation.',
        img: '/../public/project_weather.gif',
        github: 'https://github.com/armenmerzaian/weather-app',
        learnMore: '',
        launch: 'https://taupe-llama-46f0dd.netlify.app',
        images: [],
        description: '',
    },
    {
        title: 'Seneca Social',
        badges: ['ANDROID','FLUTTER', 'DART', 'FIREBASE', 'FIRESTORE','REST API'],
        text: 'A full stack social media app built with Flutter and Firebase. Supports user authentication, posting, commenting, and more!',
        img: '/../public/project_senecasocial.gif',
        github: 'https://github.com/armenmerzaian/seneca-social',
        learnMore: '',
        launch: '',
        images: [],
        description: '',
    },
    {
        title: 'Car Rental',
        badges: ['IOS','ANGULAR', 'TYPESCRIPT', 'IONIC'],
        text: 'An Angular front-end for a car rental app. Demonstrates the power of Ionic as a mobile app framework.',
        img: '/../public/project_carrental.gif',
        github: 'https://github.com/armenmerzaian/car-rental',
        learnMore: '',
        launch: '',
        images: [],
        description: '',
    },
]