import Head from 'next/head'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="w-full h-screen flex flex-col justify-center items-center bg-[#15181E] text-white">
        <h1 className="text-8xl">
          Hi, i'm <span className="text-[#3CCADD] font-bold">Armen</span>!
        </h1>
        <p className="text-3xl my-14 text-center text-white/80">
          Looks like you're a little early{" "}
          <span className="text-[#C678DD] font-bold">{":("}</span>
        </p>
        <p className="text-3xl my-2 text-center text-white/80">
          I'm working really hard to get it up and running.
        </p>
        <p className="text-3xl my-2 text-center text-white/80">
          See you soon!
        </p>
      </body>
    </>
  );
}
